import { Category } from "@mui/icons-material";

export const products = [
    {
      id: 1,
      name: "Wireless Bluetooth Foldable Headset",
      price: "₦5,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img1.png",
      brand: "Oraimo",
      Category: " Smartphones and Accessories",
    },
    {
      id: 2,
      name: "Sony Playstation 5 Disc Version",
      price: "₦755,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img2.png",
      brand: "sony",
      Category: "Gaming Gadget",
    },
    {
      id: 3,
      name: "Quest 2  Virtual Reality Headset",
      price: "₦599,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img3.png",
      brand: "Sony",
      Category: "Wearable Technology",
    },
    {
      id: 4,
      name: " VR Box 3D Virtual Reality BOX ",
      price: "₦35,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img4.png",
      brand: "Apple",
      Category: "Wearable Technology",
    },
    {
      id: 5,
      name: " VR Box 3D Virtual Reality BOX ",
      price: "₦35,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img4.png",
      brand: "Apple",
      Category: "Computer and Tablet",
    },
    {
      id: 6,
      name: " VR Box 3D Virtual Reality BOX ",
      price: "₦35,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img2.png",
      brand: "Samsung",
      Category: "Smartphones and Accessories",
    },
    {
      id: 7,
      name: " VR Box 3D Virtual Reality BOX ",
      price: "₦35,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img1.png",
      brand: "Sony",
      Category: "Smartphones and Accessories",
    },
    {
      id: 8,
      name: "1.2meters Model Luxury Gaming Desk",
      price: "₦255,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img5.png",
      brand: "Polar",
      Category: "computer and Tablet",
    },
    {
      id: 9,
      name: "Portable Laptop Stand",
      price: "₦9,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img6.png",
      brand: "Polar",
      Category: "Home Automation",
    },
    {
      id: 10,
      name: "Portable Laptop Stand",
      price: "₦9,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img7.png",
      brand: "Oraimo",
      Category: "Home Automation",
    },
    {
      id: 11,
      name: "Mini Smart Bluetooth Speaker",
      price: "₦35,000.00",
      rating: "4.8",
      reviews: "(1.2 reviews)",
      img: "./images/img8.png",
      brand: "Sony",
      Category: "Home Automation",
    },
    {
        id: 12,
        name: "Portable Laptop Stand",
        price: "₦9,000.00",
        rating: "4.8",
        reviews: "(1.2 reviews)",
        img: "./images/img7.png",
        brand: "Apple",
        Category: "Home Automation",
      },

  ];