export const shoeData = [
  {
    id: 1,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$140.00",
    newPrices: "$100",
    categories: "sneaker",
    image: "./images/AirNike1.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
  },
  {
    id: 2,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$130.00",
    newPrices: "$90",
    categories: "sneaker",
    image: "./images/flat1.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 3,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$150.00",
    newPrices: "$100",
    categories: "sneaker",
    image: "./images/AirNike3.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 4,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$160.00",
    newPrices: "$150",
    categories: "sneaker",
    image: "./images/AirNike4.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 5,
    name: "Nk Heels",
    company: "Nike",
    prevPrice: "$160.00",
    newPrices: "$100",
    categories: "heels",
    image: "./images/heels2.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 6,
    name: "Air Heels",
    company: "Adidas",
    prevPrice: "$140.00",
    newPrices: "$100",
    categories: "heels",
    image: "./images/heel9.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 7,
    name: "Ad Air Heels",
    company: "Adidas",
    prevPrice: "$140.00",
    newPrices: "$100",
    categories: "heels",
    image: "./images/heel8.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 8,
    name: "Ad Air Sandal",
    company: "Adidas",
    prevPrice: "$140.00",
    newPrices: "$100",
    categories: "sandal",
    image: "./images/sandal1.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 9,
    name: "Adidas",
    company: "Adidas",
    prevPrice: "$100.00",
    newPrices: "$90",
    categories: "flat",
    image: "./images/Adidas1.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 10,
    name: "AirJordan",
    company: "Jordan",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "flat",
    image: "./images/AirJordan1.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 11,
    name: "Nk Beadstock Sandal",
    company: "Nike",
    prevPrice: "$100.00",
    newPrices: "$50",
    categories: "sandal",
    image: "./images/sandal2.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
  },
  {
    id: 12,
    name: "Nik Heloc Heels",
    company: "Nike",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "heels",
    image: "./images/heels5.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 13,
    name: "Adidas",
    company: "Adidas",
    prevPrice: "$190.00",
    newPrices: "$100",
    categories: "sneaker",
    image: "./images/Adidas1.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
  {
    id: 14,
    name: "Adidas",
    company: "Adidas",
    prevPrice: "$190.00",
    newPrices: "$150",
    categories: "sneaker",
    image: "./images/Adidas3.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
  },
  {
    id: 15,
    name: "AirJordan",
    company: "Jordan",
    prevPrice: "$230.00",
    newPrices: "$200",
    categories: "sneaker",
    image: "./images/AirJordan3.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 16,
    name: "AirJordan",
    company: "Jordan",
    prevPrice: "$250.00",
    newPrices: "$200",
    categories: "sneaker",
    image: "./images/AirJordan4.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 17,
    name: "AirJordan",
    company: "Jordan",
    prevPrice: "$140.00",
    newPrices: "$100",
    categories: "sneaker",
    image: "./images/AirJordan5.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",

    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 18,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$160.00",
    newPrices: "$100",
    categories: "sneaker",
    image: "./images/AirNike17.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 19,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$100",
    newPrices: "$50",
    categories: "sneaker",
    image: "./images/AirNike11.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 20,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$100.00",
    newPrices: "$50",
    categories: "sneaker",
    image: "./images/AirNike14.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 21,
    name: "Adidas",
    company: "Adidas",
    prevPrice: "$100.00",
    newPrices: "$50",
    categories: "sneaker",
    image: "./images/Adidas5.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 22,
    name: "AirJordan",
    company: "Jordan",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "sneaker",
    image: "./images/AirJordan5.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 23,
    name: "Lv Air Heels",
    company: "Nike",
    prevPrice: "$140.00",
    newPrices: "$100",
    categories: "heels",
    image: "./images/heel8.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  {
    id: 24,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "sneaker",
    image: "./images/AirNike18.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  },
  // {
  //     id: 25,
  //     name: "Nike Air",
  //     company: "Nike",
  //     prevPrice: "$200.00",
  //     newPrices: "$150",
  //     categories: "heels",
  //     image: "./images/heel1.png",
  //     // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}}/></>,
  // },
  {
    id: 26,
    name: "Adidas Air",
    company: "Adidas",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "flat",
    image: "./images/flat8.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
  },
  {
    id: 27,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "flat",
    image: "./images/flat11.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    //
  },
  {
    id: 28,
    name: "Adidas Air",
    company: "Adidas",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "flat",
    image: "./images/flat1.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
  },
  {
    id: 29,
    name: "Nike Air Heels",
    company: "Adidas",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "heels",
    image: "./images/heels5.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    //
  },
  {
    id: 30,
    name: "AirJordan",
    company: "Jordan",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "sneaker",
    image: "./images/AirJordan6.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    //
  },
  {
    id: 31,
    name: "Nike Air",
    company: "Nike",
    prevPrice: "$100.00",
    newPrices: "$50",
    categories: "sneaker",
    image: "./images/AirNike18.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
  },
  {
    id: 32,
    name: "Heels",
    company: "Nike",
    prevPrice: "$200.00",
    newPrices: "$150",
    categories: "heels",
    image: "./images/heels6.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    //
  },
  {
    id: 33,
    name: " Ad Sin Sandal",
    company: "Adidas",
    prevPrice: "$120.00",
    newPrices: "$50",
    categories: "sandal",
    image: "./images/sandal2.png",
    rating: "4.8",
    reviews: "(1.2 reviews)",
    // star: <><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon style={{color:'orange'}} /><StarOutlineIcon/></>,
  },
];
